### ISSUE TITLE
[Todo] Todo-List

### ISSUE THREAD

**Issue by JaewoongLee-swift** [JaewoongLee-swift/ItBookSearchApp#1]
**Setting**
- [x] 프로젝트 파일 생성
- [x] Code-based 세팅

**Data Structure**
- [x] #2
- [x] #4

**UI**
- [x] #5
- [x] #7

**Network**
- [x] #9

**Function**
- [x] #11
- [x] #19
- [x] #13
- [x] #17
- [x] #15

**Fix**
- [x] #25
- [x] #27
- [x] #23
- [ ] #21

**Test**
- [ ] 각 기능구현 별 Unit Test 작성
