### ISSUE TITLE
[Feat] 에러 발생 시 알러트 알림 구현

### ISSUE THREAD

**Issue by JaewoongLee-swift** [JaewoongLee-swift/ItBookSearchApp#42]
**Issue : Feature**
- 현재 에러 발생 시 print로만 나타나는 에러를 알러트로 나타나도록 변경이 필요합니다.

**Description**
- API 호출, PDF 로드 실패 등에서 나타나는 에러 상황을 나타내기 위한 알러트 구현이 필요합니다.

**Todo**
- [ ] 알러트 노출 메소드 구현
- [ ] API 호출 실패시 알러트 구현
- [ ] 기타 옵셔널 바인딩 처리부분에서의 알러트 구현
