### ISSUE TITLE
[Refacotr] MVC 패턴 -> ReactorKit 프레임워크 리팩토링

### ISSUE THREAD

**Issue by JaewoongLee-swift** [JaewoongLee-swift/ItBookSearchApp#44]
**Issue : Feature**
- 현재 MVC 아키텍처로 구현되어 있는 프로젝트를 ReactorKit을 활용한 단방향 아키텍처로 리팩토링이 필요합니다.

**Description**
- ReactorKit 라이브러리에 대한 의존성이 필요합니다
- ViewController가 관리하는 로직을 Reactor로의 분리가 필요합니다.
- 각각의 View와 Reactor에 대한 테스트 코드 수정이 필요합니다.

**Todo**
- [ ] ReactorKit 의존성 추가
- [ ] ItBookAPI이 RxSwift를 활용한 데이터 전달이 가능하도록 기능 추가
- [ ] 변경된 사항에 대한 테스트

**Reference(Optional)**
- https://github.com/ReactorKit/ReactorKit
